<nav class="navbar navbar-expand-lg navbar-light bg-grey">
   <div class="container-fluid">
      <a class="navbar-brand" href="<?= $this->Helper->url(['controller' => 'main']) ?>">Framework</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false">
         <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbar">
         <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item active">
               <a class="nav-link" href="#"></a>
            </li>
         </ul>
      </div>
   </div>
</nav>