<nav class="navbar navbar-expand-lg navbar-light bg-grey shadow-sm">
   <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false">
      <span class="navbar-toggler-icon"></span>
   </button>
   <a class="navbar-brand" href="#">Framework</a>

   <div class="collapse navbar-collapse" id="navbar">
      <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
         <li class="nav-item active">
            <a class="nav-link" href="#"></a>
         </li>
      </ul>
   </div>
</nav>