<div class="row">
    <div class="col-md-12 mt-5">
    <h3 class="text-center">Users Action</h3>
    <p class="text-center">
        <a href="<?= $this->Helper->url(['controller' => 'main']) ?>" class="btn btn-link">
            Back Action
        </a>
    </p>
    <div class="card">
            <div class="card-header">
                <h3 class="h5">Usuarios</h3>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered table-sm table-hover">
                    <thead>
                        <tr>
                            <th class="text-center">Nombre</th>
                            <th class="text-center">Apellidos</th>
                            <th class="text-center">Email</th>
                            <th class="text-center">Rol</th>
                        </tr>
                    </thead>
                    <tbody class="table-group-divider">
                        <?php if ( isset($users) && is_array($users) && count($users) > 0 ): ?>
                            <?php foreach($users as $user): ?>
                                <tr>
                                <td><?= $user->name ?></td>
                                <td><?= $user->lastname ?></td>
                                <td><?= $user->email ?></td>
                                <td><?= $user->role ?></td>
                                </tr>
                            <?php endforeach; ?>
                        <?php else: ?>
                            <tr>
                                <td colspan="4">No existen usuarios</td>
                            </tr>
                        <?php endif; ?>
                    </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>